# This builds a docker image using the following parameters

version: '3.7'
services:
    rocmtest:
        image: rocmtest:grossi
        build:
          context: .
          dockerfile: dockerfile
        environment:
          DISPLAY:
          TF_FORCE_GPU_ALLOW_GROWTH: 'true'
          ROCM_PATH: 3.1.0  # For use with AMD; Comment out for CPU or NVIDIA
#        user: 1000:1000  # For use with NVIDIA; Comment out for AMD
        devices:  # For use with AMD; Comment out for CPU or NVIDIA
          - "/dev/kfd:/dev/kfd"
          - "/dev/dri:/dev/dri"
        volumes:
          - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
          - "/etc/passwd:/etc/passwd"
          - "/opt/data:/opt/data"
